server:
  port: 8080


spring:
  datasource:
    druid:
      business:
        username: root
        password: 123
        url: jdbc:mysql://localhost:3306/business?serverTimezone=UTC
        driver-class-name: com.mysql.cj.jdbc.Driver
        max-active: 20
        initial-size: 5
        min-idle: 5
      employee:
        username: root
        password: 123
        url: jdbc:mysql://localhost:3306/employee?serverTimezone=UTC
        driver-class-name: com.mysql.cj.jdbc.Driver
        max-active: 20
        initial-size: 5
        min-idle: 5
        #type: com.alibaba.druid.pool.DruidDataSource
        #SpringBoot默认不注入这些属性值,需要自己绑定
        #druid专用配置
#        initial-size: 5
#        min-idle: 5
#        max-active: 20
#        max-wait: 60000
#        time-between-eviction-runs-millis: 60000
#        min-evictable-idle-time-millis: 30000
#        validation-query: SELECT 1 FROM DUAL
#        test-while-idle: true
#        test-on-borrow: false
#        test-on-return: false
#        pool-prepared-statements: true
#        filters: stat,wall,log4j
#        max-pool-prepared-statement-per-connection-size: 20
#        use-global-data-source-stat: true
