server:
  port: 8080


spring:
  #FREEMARKER (FreeMarkerAutoConfiguration)
  freemarker:
    allow-request-override: false
    #Enable template caching.启用模板缓存。
    cache: false
    check-template-location: true
    charset: UTF-8
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    #设置面板后缀
    suffix: .ftl
    template-loader-path: classpath:/templates
  application:
    name: study_project
#  datasource:
#    druid:
#      driver-class-name:
#      url:
#      username:
#      password:
